export const getSmashystreamUrl = (tmdbID) =>{
    return `https://embed.smashystream.com/playere.php?tmdb=${tmdbID}`
}
export const getSuperembedUrl = (tmdbID) =>{
    return `https://multiembed.mov/directstream.php?video_id=${tmdbID}&tmdb=1`
}
export const get2embedUrl = (tmdbID) =>{
    return `https://www.2embed.cc/embed/${tmdbID}`
}

export const MainCarouselData = [
  {
    adult: false,
    backdrop_path: "/2QL5j6mB4ZpyBcVr0WO9H9MQGBu.jpg",
    genre_ids: [28, 12, 14],
    id: 734253,
    original_language: "hi",
    original_title: "आदिपुरुष",
    overview:
      "7000 years ago, Ayodhya's Prince Raghava and Prince Sesh along with the Mighty Vanar Warriors travels to the island of Lanka with an aim to rescue Raghava's wife Janaki, who has been abducted by Lankesh, the king of Lanka.",
    popularity: 180.203,
    poster_path: "/kpuOeWclbtLU414Txv8ZT6HoZ0k.jpg",
    release_date: "2023-06-16",
    title: "Adipurush",
    video: false,
    vote_average: 5.164,
    vote_count: 73,
  },
  {
    adult: false,
    backdrop_path: "/5LtSjMNw6j3LkG29Oa4O0iY5U8.jpg",
    genre_ids: [28, 12, 53],
    id: 872906,
    original_language: "hi",
    original_title: "जवान",
    overview:
      "An emotional journey of a prison warden, driven by a personal vendetta while keeping up to a promise made years ago, recruits inmates to commit outrageous crimes that shed light on corruption and injustice, in an attempt to get even with his past,  and that leads him to an unexpected reunion.",
    popularity: 178.857,
    poster_path: "/bilZfvrrM1YEICmj5DYVEGmGxod.jpg",
    release_date: "2023-09-07",
    title: "Jawan",
    video: false,
    vote_average: 7.232,
    vote_count: 190,
  },
  {
    adult: false,
    backdrop_path: "/yrO8MHXReLdvKhf1qtSjSrpm7gE.jpg",
    genre_ids: [18, 80],
    id: 1227136,
    original_language: "hi",
    original_title: "भक्षक",
    overview:
      "A struggling local journalist begins a dogged investigation into harrowing cases of abuse being covered up at a shelter for young girls.",
    popularity: 145.765,
    poster_path: "/tHTxBsRLquFUZ4KTWzUalK4EDZW.jpg",
    release_date: "2024-02-08",
    title: "Bhakshak",
    video: false,
    vote_average: 8.1,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: "/2n6KECWCNmekIEgZFNlldkELUsP.jpg",
    genre_ids: [28, 18],
    id: 997391,
    original_language: "ml",
    original_title: "ആര്‍ഡിഎക്സ്: റോബര്‍ട്ട് ഡോണി സേവ്യര്‍",
    overview:
      "Once-menacing, anger fueled, trained martial arts fighters Robert, Dony and Xavier settle down to peaceful lives, after a significant event prompts them. Fate orchestrates their reunion and return from exile to their fighting ways, when their history linger ominously and one of them faces a violent attack.",
    popularity: 112.033,
    poster_path: "/E4prGNIMN8USgwZBkVj3ADasAG.jpg",
    release_date: "2023-08-25",
    title: "RDX: Robert Dony Xavier",
    video: false,
    vote_average: 7.1,
    vote_count: 30,
  },
  {
    adult: false,
    backdrop_path: "/13QFKJa7ZPY3VN0L6sxKuNoLHFf.jpg",
    genre_ids: [28, 80, 18],
    id: 781732,
    original_language: "hi",
    original_title: "Animal",
    overview:
      "The hardened son of a powerful industrialist returns home after years abroad and vows to take bloody revenge on those threatening his father's life.",
    popularity: 58.462,
    poster_path: "/hr9rjR3J0xBBKmlJ4n3gHId9ccx.jpg",
    release_date: "2023-12-01",
    title: "Animal",
    video: false,
    vote_average: 6.723,
    vote_count: 74,
  },
  {
    adult: false,
    backdrop_path: "/hOx2kPyniEHJj9wquzJMuStFFUG.jpg",
    genre_ids: [28, 80, 53],
    id: 770906,
    original_language: "te",
    original_title: "Salaar: Part 1 - Ceasefire",
    overview:
      "In the city of Khansaar, Raja Mannar plans to make his son, Vardharaja Mannar his successor, but Raja Mannar's ministers and advisors plan a coup d'état by hiring armies from Russia and Serbia to attack and kill Vardha and Raja. Vardha, along with his brother and a few trusted men, manage to escape from Khansaar. Vardha goes to his childhood best friend, Deva, who learns about his predicament and sets out to make him the undisputed successor of Khansaar.",
    popularity: 55.527,
    poster_path: "/47Qhmf5OySjG5QUcfVqzqzjpCS2.jpg",
    release_date: "2023-12-21",
    title: "Salaar: Part 1 - Ceasefire",
    video: false,
    vote_average: 6.333,
    vote_count: 45,
  },
  {
    adult: false,
    backdrop_path: "/gYRdSs0nC9ovtqUa99k3Oa5hD8v.jpg",
    genre_ids: [28, 53],
    id: 1034587,
    original_language: "te",
    original_title: "అమిగోస్",
    overview:
      "Siddharth, a youngman who runs a family business is astonished to find his doppelgängers Manjunath and Michael on getdopple.com. After meeting up in Goa, they come down to Hyderabad to help Siddarth win over Ishika, a girl looking for superman to be her husband. But things take a drastic turn when NIA swings into action to nab Michael, aka Bipin Roy.",
    popularity: 54.907,
    poster_path: "/vVBOUGpDRQTq2m8uRTmiqJaYphS.jpg",
    release_date: "2023-02-10",
    title: "Amigos",
    video: false,
    vote_average: 4.8,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: "/77GGKq6Ixq6ZiqBM6XcPZgQmiN2.jpg",
    genre_ids: [28, 18],
    id: 579974,
    original_language: "te",
    original_title: "రౌద్రం రణం రుధిరం",
    overview:
      "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.",
    popularity: 49.105,
    poster_path: "/ljHw5eIMnki3HekwkKwCCHsRSbH.jpg",
    release_date: "2022-03-24",
    title: "RRR",
    video: false,
    vote_average: 7.789,
    vote_count: 1161,
  },
  {
    adult: false,
    backdrop_path: "/sDiGcjWhSu42dCw0jQmBInAkDZ9.jpg",
    genre_ids: [28, 53],
    id: 379149,
    original_language: "en",
    original_title: "The Foreigner",
    overview:
      "Quan is a humble London businessman whose long-buried past erupts in a revenge-fueled vendetta when the only person left for him to love – his teenage daughter – dies in an Irish Republican Army car bombing. His relentless search to find the terrorists leads to a cat-and-mouse conflict with a British government official whose own past may hold the clues to the identities of the elusive killers.",
    popularity: 47.094,
    poster_path: "/rwM4hzrmc5HiWfQD9ls9DL4QgGl.jpg",
    release_date: "2017-09-28",
    title: "The Foreigner",
    video: false,
    vote_average: 6.964,
    vote_count: 2476,
  },
  {
    adult: false,
    backdrop_path: "/lcyippCCbZOliGxX7HbTNyWf98q.jpg",
    genre_ids: [12, 18],
    id: 87827,
    original_language: "en",
    original_title: "Life of Pi",
    overview:
      "The story of an Indian boy named Pi, a zookeeper's son who finds himself in the company of a hyena, zebra, orangutan, and a Bengal tiger after a shipwreck sets them adrift in the Pacific Ocean.",
    popularity: 44.621,
    poster_path: "/iLgRu4hhSr6V1uManX6ukDriiSc.jpg",
    release_date: "2012-11-20",
    title: "Life of Pi",
    video: false,
    vote_average: 7.397,
    vote_count: 12622,
  },
  {
    adult: false,
    backdrop_path: "/u3lWiLi0e0W3aU822QdcxQIGBES.jpg",
    genre_ids: [28, 12],
    id: 962074,
    original_language: "ta",
    original_title: "கேப்டன் மில்லர்",
    overview:
      'In the 1930s, during the British Raj, Analeesan "Eesa", a former soldier of the British Indian Army called Captain Miller, is on a mission to protect the people from the British after witnessing an atrocity.',
    popularity: 42.397,
    poster_path: "/gq5OlT5ImxsNpkirpgf4rYngd3M.jpg",
    release_date: "2024-01-11",
    title: "Captain Miller",
    video: false,
    vote_average: 7.286,
    vote_count: 14,
  },
  {
    adult: false,
    backdrop_path: "/ba9TgAO4I8RyA2LljzR3MspHaM9.jpg",
    genre_ids: [28, 878, 53],
    id: 799155,
    original_language: "hi",
    original_title: "Attack",
    overview:
      "With the Parliament under siege, India’s first super soldier Arjun Shergill is tasked to get hold of the terrorists in the nick of time, save the Prime Minister from their clutches and stop a dirty bomb from exploding and destroying Delhi. Will Arjun succeed in his mission?",
    popularity: 41.03,
    poster_path: "/5jGKbYuZtdxSNOocI6ZziQeiY4n.jpg",
    release_date: "2022-04-01",
    title: "Attack",
    video: false,
    vote_average: 7.155,
    vote_count: 129,
  },
  {
    adult: false,
    backdrop_path: "/qLkVnDIpfpOjCpH3MfApW8jUir1.jpg",
    genre_ids: [27, 14, 36],
    id: 1166133,
    original_language: "ml",
    original_title: "ഭ്രമയുഗം",
    overview:
      "Thevan, a folk singer of the Paanan caste, has a fateful encounter when escaping slavery, leading to discover an ancient tradition altering his destiny.",
    popularity: 40.282,
    poster_path: "/snQLwRrfQAl5YFKVefZq9Lbscki.jpg",
    release_date: "2024-02-15",
    title: "Bramayugam",
    video: false,
    vote_average: 8,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/9IZvClXvhSxlp41eT0CyUEsyjqy.jpg",
    genre_ids: [18, 10749],
    id: 12405,
    original_language: "en",
    original_title: "Slumdog Millionaire",
    overview:
      'A teenager reflects on his life after being accused of cheating on the Indian version of "Who Wants to be a Millionaire?".',
    popularity: 35.216,
    poster_path: "/5leCCi7ZF0CawAfM5Qo2ECKPprc.jpg",
    release_date: "2008-11-12",
    title: "Slumdog Millionaire",
    video: false,
    vote_average: 7.731,
    vote_count: 10144,
  },
  {
    adult: false,
    backdrop_path: "/uVQYYe56a0mchLNlwIyWsTswLtx.jpg",
    genre_ids: [18, 10751, 28, 10749],
    id: 371676,
    original_language: "te",
    original_title: "సోమరి",
    overview:
      "Raja, who thinks his mother is dead, turns into a thief. However, his life changes when he falls for Mounika, a girl who is escaping a forced marriage, and eventually meets her aunt.",
    popularity: 34.542,
    poster_path: "/qXrIBBugDIgjd7mm6XqDj256gCx.jpg",
    release_date: "2015-12-18",
    title: "Loafer",
    video: false,
    vote_average: 5.8,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/nvwxkjJKvNOB5uoTsT6JAhfpQ3D.jpg",
    genre_ids: [14, 35, 27],
    id: 1030109,
    original_language: "te",
    original_title: "ఊరు పేరు భైరవకోన",
    overview:
      "A man goes in search of some urgently required answers to the world of Bhairavakona, from which there's seemingly no way out.",
    popularity: 34.301,
    poster_path: "/gUmeT4kEUNPUA9lTzq9Qk4ZoU7T.jpg",
    release_date: "2024-02-16",
    title: "Ooru Peru Bhairavakona",
    video: false,
    vote_average: 7,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/pRb9zpNXH1u6Fd4Da9H8PaIDwoY.jpg",
    genre_ids: [28, 18],
    id: 868660,
    original_language: "te",
    original_title: "గుంటూరు కారం",
    overview:
      "Years after his mother left him and remarried, Ramana is asked to sign documents denying any relations with his mother, but he refuses and demands answer to why his mother left him.",
    popularity: 33.527,
    poster_path: "/6wRGuOf5k9x04A3wz6w7BrzRRJ2.jpg",
    release_date: "2024-01-11",
    title: "Guntur Kaaram",
    video: false,
    vote_average: 7,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: "/e9ZEuHGHZ06AToHlfN1L7nejJ7W.jpg",
    genre_ids: [28, 12, 14],
    id: 256040,
    original_language: "te",
    original_title: "బాహుబలి:ద బిగినింగ్",
    overview:
      "The young Shivudu is left as a foundling in a small village by his mother. By the time he’s grown up, it has become apparent that he possesses exceptional gifts. He meets the beautiful warrior princess Avanthika and learns that her queen has been held captive for the last 25 years. Shividu sets off to rescue her, discovering his own origins in the process.",
    popularity: 32.918,
    poster_path: "/9BAjt8nSSms62uOVYn1t3C3dVto.jpg",
    release_date: "2015-07-10",
    title: "Bāhubali: The Beginning",
    video: false,
    vote_average: 7.555,
    vote_count: 752,
  },
  {
    adult: false,
    backdrop_path: "/5qjbu7po6eqLNd4kUPAyIpFRwQK.jpg",
    genre_ids: [18, 10751, 35, 28],
    id: 360814,
    original_language: "hi",
    original_title: "दंगल",
    overview:
      "Dangal is an extraordinary true story based on the life of Mahavir Singh and his two daughters, Geeta and Babita Phogat. The film traces the inspirational journey of a father who trains his daughters to become world class wrestlers.",
    popularity: 32.761,
    poster_path: "/cJRPOLEexI7qp2DKtFfCh7YaaUG.jpg",
    release_date: "2016-12-21",
    title: "Dangal",
    video: false,
    vote_average: 7.927,
    vote_count: 893,
  },
  {
    adult: false,
    backdrop_path: "/yCRYYGldFGVa4cmZVpTVCRQMfjA.jpg",
    genre_ids: [28, 12, 14],
    id: 350312,
    original_language: "te",
    original_title: "బాహుబలి 2: ది కన్ క్లూజన్",
    overview:
      "When Mahendra, the son of Bāhubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.",
    popularity: 31.996,
    poster_path: "/21sC2assImQIYCEDA84Qh9d1RsK.jpg",
    release_date: "2017-04-27",
    title: "Bāhubali 2: The Conclusion",
    video: false,
    vote_average: 7.398,
    vote_count: 697,
  },
];